import {
  renderDiagnostic as renderSourceDiagnostic,
  type Diagnostic,
} from "./source.ts";

export type { DiagnosticCode } from "./source.ts";
export type { ByteRange } from "./source.ts";
export type { Position } from "./source.ts";
export type { SourceRange } from "./source.ts";
export type { Diagnostic } from "./source.ts";
export type { SourceInput } from "./source.ts";
export type { HintProvenance } from "./syntax.ts";
export type { HintName } from "./syntax.ts";
export type { Hint } from "./syntax.ts";
export type { SyntaxCallTarget } from "./syntax.ts";
export type { BinaryOperator } from "./syntax.ts";
export type { UnaryOperator } from "./syntax.ts";
export type { LogicalOperator } from "./syntax.ts";
export type { AssignmentOperator } from "./syntax.ts";
export type { UpdateOperator } from "./syntax.ts";
export type { SyntaxArraySpreadElement } from "./syntax.ts";
export type { SyntaxArrayElement } from "./syntax.ts";
export type { SyntaxSpreadArgument } from "./syntax.ts";
export type { SyntaxCallArgument } from "./syntax.ts";
export type { SyntaxObjectDefinition } from "./syntax.ts";
export type { SyntaxObjectSpreadProperty } from "./syntax.ts";
export type { SyntaxObjectProperty } from "./syntax.ts";
export type { SyntaxClassMethod } from "./syntax.ts";
export type { SyntaxClassElement } from "./syntax.ts";
export type { SyntaxExpression } from "./syntax.ts";
export type { SyntaxParameter } from "./syntax.ts";
export type { SyntaxBindingIdentifier } from "./syntax.ts";
export type { SyntaxAssignmentMemberTarget } from "./syntax.ts";
export type { SyntaxBindingElement } from "./syntax.ts";
export type { SyntaxArrayBindingPattern } from "./syntax.ts";
export type { SyntaxObjectBindingProperty } from "./syntax.ts";
export type { SyntaxObjectBindingPattern } from "./syntax.ts";
export type { SyntaxBindingTarget } from "./syntax.ts";
export type { SyntaxAssignmentTarget } from "./syntax.ts";
export type { SyntaxBindingPattern } from "./syntax.ts";
export type { SyntaxAssignmentPattern } from "./syntax.ts";
export type { HirBindingIdentifier } from "./hir.ts";
export type { HirAssignmentMemberTarget } from "./hir.ts";
export type { HirBindingElement } from "./hir.ts";
export type { HirArrayBindingPattern } from "./hir.ts";
export type { HirObjectBindingProperty } from "./hir.ts";
export type { HirObjectBindingPattern } from "./hir.ts";
export type { HirBindingTarget } from "./hir.ts";
export type { HirBindingPattern } from "./hir.ts";
export type { BindingPatternMode } from "./syntax.ts";
export type { SyntaxSwitchCase } from "./syntax.ts";
export type { HirSwitchCase } from "./hir.ts";
export type { SyntaxForDeclaration } from "./syntax.ts";
export type { HirForDeclaration } from "./hir.ts";
export type { SyntaxForOfTarget } from "./syntax.ts";
export type { HirForOfTarget } from "./hir.ts";
export type { FunctionKind } from "./syntax.ts";
export type { SyntaxStatement } from "./syntax.ts";
export type { SyntaxFunction } from "./syntax.ts";
export type { SyntaxProgram } from "./syntax.ts";
export type { FrontendResult } from "./syntax.ts";
export type { SourceFrontend } from "./syntax.ts";
export type { SyntaxModuleSpecifier } from "./syntax.ts";
export type { SyntaxImportEntry } from "./syntax.ts";
export type { SyntaxExportEntry } from "./syntax.ts";
export type { SyntaxModule } from "./syntax.ts";
export type { ModuleFrontendResult } from "./syntax.ts";
export type { ModuleSourceFrontend } from "./syntax.ts";
export type { LoadedModuleSource } from "./syntax.ts";
export type { ModuleLoadResult } from "./syntax.ts";
export type { ModuleLoadReferrer } from "./syntax.ts";
export type { ModuleLoader } from "./syntax.ts";
export type { ModuleResolutionResult } from "./syntax.ts";
export type { ModuleResolver } from "./syntax.ts";
export type { ModuleDependency } from "./syntax.ts";
export type { ModuleResolution } from "./syntax.ts";
export type { ModuleGraphNode } from "./syntax.ts";
export type { ModuleGraph } from "./syntax.ts";
export type { ModuleGraphResult } from "./syntax.ts";
export { buildModuleGraph } from "./modules.ts";
export type { LinkedModuleCell } from "./modules.ts";
export type { LinkedModuleImport } from "./modules.ts";
export type { LinkedModuleExport } from "./modules.ts";
export type { LinkedModule } from "./modules.ts";
export type { ModuleComponent } from "./modules.ts";
export type { LinkedModuleGraph } from "./modules.ts";
export type { ModuleLinkResult } from "./modules.ts";
export { linkModuleGraph } from "./modules.ts";
export type { ErrorIntrinsicName } from "./hir.ts";
export type { HirCallTarget } from "./hir.ts";
export type { HirArraySpreadElement } from "./hir.ts";
export type { HirArrayElement } from "./hir.ts";
export type { HirSpreadArgument } from "./hir.ts";
export type { HirCallArgument } from "./hir.ts";
export type { HirObjectDefinition } from "./hir.ts";
export type { HirObjectSpreadProperty } from "./hir.ts";
export type { HirObjectProperty } from "./hir.ts";
export type { HirClassMethod } from "./hir.ts";
export type { HirClassElement } from "./hir.ts";
export type { HirClassNameBinding } from "./hir.ts";
export type { HirExpression } from "./hir.ts";
export type { HirStatement } from "./hir.ts";
export type { HirParameter } from "./hir.ts";
export type { HirFunction } from "./hir.ts";
export type { HirGlobalBinding } from "./hir.ts";
export type { HirProgram } from "./hir.ts";
export type { HirResult } from "./hir.ts";
export { buildHir } from "./hir-build.ts";
export { printHir } from "./hir-print.ts";
export type { MirConstant } from "./mir.ts";
export type { MirCallTarget } from "./mir.ts";
export type { MirHint } from "./mir.ts";
export type { SpecializationMode } from "./mir.ts";
export type { CompilerOptions } from "./mir.ts";
export type { MirParameter } from "./mir.ts";
export type { MirGlobalBinding } from "./mir.ts";
export type { MirControlTarget } from "./mir.ts";
export type { MirOperation } from "./mir.ts";
export type { MirTerminator } from "./mir.ts";
export type { MirBlock } from "./mir.ts";
export type { MirSpecialization } from "./mir.ts";
export type { MirFunction } from "./mir.ts";
export type { MirProgram } from "./mir.ts";
export { buildMir } from "./mir-build.ts";
export { printMir } from "./mir-print.ts";
export type { CompilationResult } from "./module-compile.ts";
export type { ModuleCompilationResult } from "./module-compile.ts";
export { compileModuleGraph } from "./module-compile.ts";
export { compileSource } from "./compile.ts";
export type { NativeArchitecture } from "./native.ts";
export type { NativeOperatingSystem } from "./native.ts";
export type { NativeAbi } from "./native.ts";
export type { TargetName } from "./native.ts";
export type { ExecutionHostDescription } from "./native.ts";
export type { TargetDescription } from "./native.ts";
export type { EmittedNativeSource } from "./native.ts";
export type { NativeBackend } from "./native.ts";
export type { RuntimeAsset } from "./native.ts";
export type { RuntimeArchiveAsset } from "./native.ts";
export type { RuntimeArchiveKeyInput } from "./native.ts";
export type { RuntimeArchiveReuse } from "./native.ts";
export type { RuntimeInput } from "./native.ts";
export type { RuntimeInputProvider } from "./native.ts";
export type { CompilerCache } from "./native.ts";
export type { CompilerCacheLock } from "./native.ts";
export type { ProcessEnvironment } from "./native.ts";
export type { ProcessEnvironmentPolicy } from "./native.ts";
export type { ProcessRequest } from "./native.ts";
export type { ProcessObservation } from "./native.ts";
export type { NativeBuildPlan } from "./native.ts";
export type { NativeBuildInput } from "./native.ts";
export type { NativeToolchain } from "./native.ts";
export type { CompilerHost } from "./native.ts";
/** Render the stable first line of an Oseo diagnostic. */
export function renderDiagnostic(diagnostic: Diagnostic): string {
  return renderSourceDiagnostic(diagnostic);
}
export { describeTarget } from "./native.ts";
export { canExecuteTarget } from "./native.ts";
export { targetForExecutionHost } from "./native.ts";
