/**
 * Derived seconds from summed measured case durations in CI runs
 * 36243816479 and 36261458909. Each entry keeps the larger observation.
 * See docs/evidence/u6/README.md; these weights are not job wall times.
 */
export const nativeShardCosts = {
  "linux-x86_64-gnu": {
    "tests/property/m4-async.property.test.ts": 465,
    "tests/property/m5-aggregate-error.property.test.ts": 274,
    "tests/property/m5-arguments-object.property.test.ts": 464,
    "tests/property/m5-array-binding.property.test.ts": 242,
    "tests/property/m5-array-buffer.property.test.ts": 629,
    "tests/property/m5-array-constructor.property.test.ts": 571,
    "tests/property/m5-array-prototype-change-by-copy.property.test.ts": 325,
    "tests/property/m5-array-prototype-copying.property.test.ts": 420,
    "tests/property/m5-array-prototype-index-search.property.test.ts": 446,
    "tests/property/m5-array-prototype-iterative.property.test.ts": 488,
    "tests/property/m5-array-prototype-iterators.property.test.ts": 308,
    "tests/property/m5-array-prototype-mutation.property.test.ts": 469,
    "tests/property/m5-array-prototype-predicate-search.property.test.ts": 472,
    "tests/property/m5-array-prototype-reduction.property.test.ts": 408,
    "tests/property/m5-array-prototype-sort.property.test.ts": 277,
    "tests/property/m5-array-prototype-species-mapping.property.test.ts": 586,
    "tests/property/m5-array-spread.property.test.ts": 253,
    "tests/property/m5-async-await.property.test.ts": 290,
    "tests/property/m5-async-generator.property.test.ts": 177,
    "tests/property/m5-atomics-and-shared-memory.property.test.ts": 492,
    "tests/property/m5-atomics-single-agent.property.test.ts": 430,
    "tests/property/m5-bigint-intrinsic.property.test.ts": 545,
    "tests/property/m5-bigint.property.test.ts": 55,
    "tests/property/m5-boolean-intrinsic.property.test.ts": 418,
    "tests/property/m5-call-spread.property.test.ts": 239,
    "tests/property/m5-catch-binding.property.test.ts": 159,
    "tests/property/m5-class.property.test.ts": 548,
    "tests/property/m5-compound-assignment.property.test.ts": 174,
    "tests/property/m5-data-view.property.test.ts": 570,
    "tests/property/m5-date-family.property.test.ts": 621,
    "tests/property/m5-default-parameter.property.test.ts": 105,
    "tests/property/m5-delete-super.property.test.ts": 442,
    "tests/property/m5-delete.property.test.ts": 349,
    "tests/property/m5-destructuring-assignment.property.test.ts": 184,
    "tests/property/m5-ephemeron-tracing.property.test.ts": 29,
    "tests/property/m5-export-default-class.property.test.ts": 45,
    "tests/property/m5-for-await-of.property.test.ts": 1070,
    "tests/property/m5-for-binding.property.test.ts": 218,
    "tests/property/m5-for-in-object-pattern.property.test.ts": 537,
    "tests/property/m5-for-in.property.test.ts": 609,
    "tests/property/m5-for-of-assignment.property.test.ts": 238,
    "tests/property/m5-for-of-binding.property.test.ts": 215,
    "tests/property/m5-for-of.property.test.ts": 147,
    "tests/property/m5-function-intrinsic-chains.property.test.ts": 518,
    "tests/property/m5-function-prototype.property.test.ts": 372,
    "tests/property/m5-generator-methods.property.test.ts": 51,
    "tests/property/m5-generator-parameter.property.test.ts": 148,
    "tests/property/m5-generator-throw.property.test.ts": 46,
    "tests/property/m5-generator.property.test.ts": 382,
    "tests/property/m5-generic-string-coercion.property.test.ts": 331,
    "tests/property/m5-global-numeric-functions.property.test.ts": 483,
    "tests/property/m5-global-object-record.property.test.ts": 422,
    "tests/property/m5-globalthis-binding.property.test.ts": 532,
    "tests/property/m5-harness-native-function-matcher.property.test.ts": 861,
    "tests/property/m5-harness-promise-helper.property.test.ts": 428,
    "tests/property/m5-intrinsic-graph-root.property.test.ts": 305,
    "tests/property/m5-iterator-helpers-eager.property.test.ts": 339,
    "tests/property/m5-iterator-helpers-lazy.property.test.ts": 323,
    "tests/property/m5-iterator-intrinsic.property.test.ts": 262,
    "tests/property/m5-json-parse.property.test.ts": 373,
    "tests/property/m5-json-stringify.property.test.ts": 343,
    "tests/property/m5-lexical-declaration-list.property.test.ts": 532,
    "tests/property/m5-lexical-super.property.test.ts": 356,
    "tests/property/m5-map-intrinsic.property.test.ts": 384,
    "tests/property/m5-math-namespace.property.test.ts": 1152,
    "tests/property/m5-module-continuation.property.test.ts": 226,
    "tests/property/m5-number-intrinsic.property.test.ts": 678,
    "tests/property/m5-number-prototype.property.test.ts": 712,
    "tests/property/m5-object-binding.property.test.ts": 170,
    "tests/property/m5-object-constructor.property.test.ts": 1281,
    "tests/property/m5-object-create.property.test.ts": 307,
    "tests/property/m5-object-define-properties.property.test.ts": 449,
    "tests/property/m5-object-define-property.property.test.ts": 415,
    "tests/property/m5-object-descriptor-queries.property.test.ts": 521,
    "tests/property/m5-object-integrity-levels.property.test.ts": 421,
    "tests/property/m5-object-literal.property.test.ts": 922,
    "tests/property/m5-object-own-keys.property.test.ts": 3327,
    "tests/property/m5-object-prototype.property.test.ts": 321,
    "tests/property/m5-object-rest.property.test.ts": 140,
    "tests/property/m5-optional-catch-binding.property.test.ts": 168,
    "tests/property/m5-optional-chaining.property.test.ts": 200,
    "tests/property/m5-optional-private.property.test.ts": 246,
    "tests/property/m5-parameter-binding.property.test.ts": 117,
    "tests/property/m5-parameter-var.property.test.ts": 151,
    "tests/property/m5-pattern-await.property.test.ts": 511,
    "tests/property/m5-promise-combine.property.test.ts": 1273,
    "tests/property/m5-promise-intrinsic.property.test.ts": 989,
    "tests/property/m5-proxy-exotic-object.property.test.ts": 1718,
    "tests/property/m5-reflect-namespace.property.test.ts": 2299,
    "tests/property/m5-regexp-intrinsic.property.test.ts": 351,
    "tests/property/m5-regexp-literal-aot.property.test.ts": 348,
    "tests/property/m5-regexp-matcher.property.test.ts": 7,
    "tests/property/m5-regexp-pattern-extensions.property.test.ts": 1,
    "tests/property/m5-regexp-pattern.property.test.ts": 2,
    "tests/property/m5-regexp-prototype-and-exec.property.test.ts": 446,
    "tests/property/m5-regexp-symbol-methods.property.test.ts": 740,
    "tests/property/m5-regexp-unicode-property-escapes.property.test.ts": 2,
    "tests/property/m5-rest-parameter.property.test.ts": 146,
    "tests/property/m5-runtime-error-observation.property.test.ts": 270,
    "tests/property/m5-set-composition-methods.property.test.ts": 481,
    "tests/property/m5-set-intrinsic.property.test.ts": 356,
    "tests/property/m5-string-intrinsic.property.test.ts": 814,
    "tests/property/m5-string-iterator.property.test.ts": 285,
    "tests/property/m5-string-prototype-access.property.test.ts": 604,
    "tests/property/m5-string-prototype-case.property.test.ts": 314,
    "tests/property/m5-string-prototype-match-and-split.property.test.ts": 1026,
    "tests/property/m5-string-prototype-pad.property.test.ts": 257,
    "tests/property/m5-string-prototype-replace.property.test.ts": 880,
    "tests/property/m5-string-prototype-search-and-slice.property.test.ts": 568,
    "tests/property/m5-super-targets.property.test.ts": 537,
    "tests/property/m5-super-without-extends.property.test.ts": 212,
    "tests/property/m5-symbol-intrinsic.property.test.ts": 446,
    "tests/property/m5-tagged-template.property.test.ts": 181,
    "tests/property/m5-top-level-this.property.test.ts": 631,
    "tests/property/m5-typed-array-constructors.property.test.ts": 445,
    "tests/property/m5-typed-array-core.property.test.ts": 369,
    "tests/property/m5-typed-array-iterative.property.test.ts": 350,
    "tests/property/m5-typed-array-mutation.property.test.ts": 359,
    "tests/property/m5-typed-array-search-and-join.property.test.ts": 286,
    "tests/property/m5-typed-array-sort.property.test.ts": 299,
    "tests/property/m5-typed-array-statics.property.test.ts": 430,
    "tests/property/m5-typeof-unresolved.property.test.ts": 375,
    "tests/property/m5-update-expression.property.test.ts": 140,
    "tests/property/m5-uri-handling-functions.property.test.ts": 436,
    "tests/property/m5-weak-collections.property.test.ts": 469,
    "tests/property/m5-well-known-symbols.property.test.ts": 452,
    "tests/property/nio-clock-wakeup.property.test.ts": 145,
    "tests/property/unicode-tables.property.test.ts": 1,
  },
  "macos-aarch64": {
    "tests/property/m4-async.property.test.ts": 283,
    "tests/property/m5-aggregate-error.property.test.ts": 251,
    "tests/property/m5-arguments-object.property.test.ts": 645,
    "tests/property/m5-array-binding.property.test.ts": 212,
    "tests/property/m5-array-buffer.property.test.ts": 466,
    "tests/property/m5-array-constructor.property.test.ts": 391,
    "tests/property/m5-array-prototype-change-by-copy.property.test.ts": 359,
    "tests/property/m5-array-prototype-copying.property.test.ts": 267,
    "tests/property/m5-array-prototype-index-search.property.test.ts": 403,
    "tests/property/m5-array-prototype-iterative.property.test.ts": 376,
    "tests/property/m5-array-prototype-iterators.property.test.ts": 306,
    "tests/property/m5-array-prototype-mutation.property.test.ts": 318,
    "tests/property/m5-array-prototype-predicate-search.property.test.ts": 299,
    "tests/property/m5-array-prototype-reduction.property.test.ts": 358,
    "tests/property/m5-array-prototype-sort.property.test.ts": 308,
    "tests/property/m5-array-prototype-species-mapping.property.test.ts": 461,
    "tests/property/m5-array-spread.property.test.ts": 251,
    "tests/property/m5-async-await.property.test.ts": 239,
    "tests/property/m5-async-generator.property.test.ts": 248,
    "tests/property/m5-atomics-and-shared-memory.property.test.ts": 336,
    "tests/property/m5-atomics-single-agent.property.test.ts": 407,
    "tests/property/m5-bigint-intrinsic.property.test.ts": 465,
    "tests/property/m5-bigint.property.test.ts": 94,
    "tests/property/m5-boolean-intrinsic.property.test.ts": 322,
    "tests/property/m5-call-spread.property.test.ts": 178,
    "tests/property/m5-catch-binding.property.test.ts": 202,
    "tests/property/m5-class.property.test.ts": 820,
    "tests/property/m5-compound-assignment.property.test.ts": 192,
    "tests/property/m5-data-view.property.test.ts": 452,
    "tests/property/m5-date-family.property.test.ts": 479,
    "tests/property/m5-default-parameter.property.test.ts": 174,
    "tests/property/m5-delete-super.property.test.ts": 313,
    "tests/property/m5-delete.property.test.ts": 358,
    "tests/property/m5-destructuring-assignment.property.test.ts": 198,
    "tests/property/m5-ephemeron-tracing.property.test.ts": 40,
    "tests/property/m5-export-default-class.property.test.ts": 61,
    "tests/property/m5-for-await-of.property.test.ts": 806,
    "tests/property/m5-for-binding.property.test.ts": 212,
    "tests/property/m5-for-in-object-pattern.property.test.ts": 753,
    "tests/property/m5-for-in.property.test.ts": 451,
    "tests/property/m5-for-of-assignment.property.test.ts": 190,
    "tests/property/m5-for-of-binding.property.test.ts": 191,
    "tests/property/m5-for-of.property.test.ts": 175,
    "tests/property/m5-function-intrinsic-chains.property.test.ts": 374,
    "tests/property/m5-function-prototype.property.test.ts": 309,
    "tests/property/m5-generator-methods.property.test.ts": 71,
    "tests/property/m5-generator-parameter.property.test.ts": 174,
    "tests/property/m5-generator-throw.property.test.ts": 64,
    "tests/property/m5-generator.property.test.ts": 293,
    "tests/property/m5-generic-string-coercion.property.test.ts": 270,
    "tests/property/m5-global-numeric-functions.property.test.ts": 682,
    "tests/property/m5-global-object-record.property.test.ts": 321,
    "tests/property/m5-globalthis-binding.property.test.ts": 485,
    "tests/property/m5-harness-native-function-matcher.property.test.ts": 638,
    "tests/property/m5-harness-promise-helper.property.test.ts": 431,
    "tests/property/m5-intrinsic-graph-root.property.test.ts": 226,
    "tests/property/m5-iterator-helpers-eager.property.test.ts": 287,
    "tests/property/m5-iterator-helpers-lazy.property.test.ts": 229,
    "tests/property/m5-iterator-intrinsic.property.test.ts": 309,
    "tests/property/m5-json-parse.property.test.ts": 265,
    "tests/property/m5-json-stringify.property.test.ts": 252,
    "tests/property/m5-lexical-declaration-list.property.test.ts": 438,
    "tests/property/m5-lexical-super.property.test.ts": 451,
    "tests/property/m5-map-intrinsic.property.test.ts": 243,
    "tests/property/m5-math-namespace.property.test.ts": 1151,
    "tests/property/m5-module-continuation.property.test.ts": 202,
    "tests/property/m5-number-intrinsic.property.test.ts": 802,
    "tests/property/m5-number-prototype.property.test.ts": 560,
    "tests/property/m5-object-binding.property.test.ts": 165,
    "tests/property/m5-object-constructor.property.test.ts": 956,
    "tests/property/m5-object-create.property.test.ts": 353,
    "tests/property/m5-object-define-properties.property.test.ts": 340,
    "tests/property/m5-object-define-property.property.test.ts": 295,
    "tests/property/m5-object-descriptor-queries.property.test.ts": 419,
    "tests/property/m5-object-integrity-levels.property.test.ts": 540,
    "tests/property/m5-object-literal.property.test.ts": 740,
    "tests/property/m5-object-own-keys.property.test.ts": 3566,
    "tests/property/m5-object-prototype.property.test.ts": 292,
    "tests/property/m5-object-rest.property.test.ts": 166,
    "tests/property/m5-optional-catch-binding.property.test.ts": 156,
    "tests/property/m5-optional-chaining.property.test.ts": 194,
    "tests/property/m5-optional-private.property.test.ts": 201,
    "tests/property/m5-parameter-binding.property.test.ts": 154,
    "tests/property/m5-parameter-var.property.test.ts": 136,
    "tests/property/m5-pattern-await.property.test.ts": 370,
    "tests/property/m5-promise-combine.property.test.ts": 860,
    "tests/property/m5-promise-intrinsic.property.test.ts": 1015,
    "tests/property/m5-proxy-exotic-object.property.test.ts": 1225,
    "tests/property/m5-reflect-namespace.property.test.ts": 2283,
    "tests/property/m5-regexp-intrinsic.property.test.ts": 315,
    "tests/property/m5-regexp-literal-aot.property.test.ts": 367,
    "tests/property/m5-regexp-matcher.property.test.ts": 6,
    "tests/property/m5-regexp-pattern-extensions.property.test.ts": 1,
    "tests/property/m5-regexp-pattern.property.test.ts": 2,
    "tests/property/m5-regexp-prototype-and-exec.property.test.ts": 472,
    "tests/property/m5-regexp-symbol-methods.property.test.ts": 536,
    "tests/property/m5-regexp-unicode-property-escapes.property.test.ts": 1,
    "tests/property/m5-rest-parameter.property.test.ts": 124,
    "tests/property/m5-runtime-error-observation.property.test.ts": 290,
    "tests/property/m5-set-composition-methods.property.test.ts": 351,
    "tests/property/m5-set-intrinsic.property.test.ts": 331,
    "tests/property/m5-string-intrinsic.property.test.ts": 714,
    "tests/property/m5-string-iterator.property.test.ts": 294,
    "tests/property/m5-string-prototype-access.property.test.ts": 437,
    "tests/property/m5-string-prototype-case.property.test.ts": 248,
    "tests/property/m5-string-prototype-match-and-split.property.test.ts": 787,
    "tests/property/m5-string-prototype-pad.property.test.ts": 271,
    "tests/property/m5-string-prototype-replace.property.test.ts": 633,
    "tests/property/m5-string-prototype-search-and-slice.property.test.ts": 389,
    "tests/property/m5-super-targets.property.test.ts": 382,
    "tests/property/m5-super-without-extends.property.test.ts": 218,
    "tests/property/m5-symbol-intrinsic.property.test.ts": 339,
    "tests/property/m5-tagged-template.property.test.ts": 153,
    "tests/property/m5-top-level-this.property.test.ts": 670,
    "tests/property/m5-typed-array-constructors.property.test.ts": 465,
    "tests/property/m5-typed-array-core.property.test.ts": 316,
    "tests/property/m5-typed-array-iterative.property.test.ts": 273,
    "tests/property/m5-typed-array-mutation.property.test.ts": 278,
    "tests/property/m5-typed-array-search-and-join.property.test.ts": 229,
    "tests/property/m5-typed-array-sort.property.test.ts": 270,
    "tests/property/m5-typed-array-statics.property.test.ts": 291,
    "tests/property/m5-typeof-unresolved.property.test.ts": 290,
    "tests/property/m5-update-expression.property.test.ts": 137,
    "tests/property/m5-uri-handling-functions.property.test.ts": 538,
    "tests/property/m5-weak-collections.property.test.ts": 378,
    "tests/property/m5-well-known-symbols.property.test.ts": 450,
    "tests/property/nio-clock-wakeup.property.test.ts": 159,
    "tests/property/unicode-tables.property.test.ts": 1,
  },
};

/**
 * Derived case-shard weights from the U6 concurrent-duration table above.
 * These are scheduling estimates, not measured case-shard job times.
 */
interface OwnKeyCaseShardCosts {
  readonly "linux-x86_64-gnu": number;
  readonly "macos-aarch64": number;
}

/** Derived one-third own-key costs for dedicated case-shard job planning. */
export const ownKeyCaseShardCosts: OwnKeyCaseShardCosts = {
  "linux-x86_64-gnu": Math.ceil(
    nativeShardCosts["linux-x86_64-gnu"][
      "tests/property/m5-object-own-keys.property.test.ts"
    ] / 3,
  ),
  "macos-aarch64": Math.ceil(
    nativeShardCosts["macos-aarch64"][
      "tests/property/m5-object-own-keys.property.test.ts"
    ] / 3,
  ),
};
